version: '3.6'

services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  #
  # Based on https://github.com/DeepLcom/deepl-mock build as public image by Stefan BÃ¼rk <stefan@buerk.tech>.
  deeplmockserver:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-deeplmockserver
    image: ghcr.io/web-vision/wv-deeplmockapi-server:latest
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

  # Ensure that mockserver is started and have connection to the web service.
  web:
    depends_on:
      - deeplmockserver
    links:
      - deeplmockserver:deeplmockserver
